// ai-partner/src/components/Chat/ChatMessage/index.vue
<template>
    <div :class="`message ${message.role === 'assistant' ? 'bot' : message.role === 'system-error' ? 'error' : 'user'}-message`">  
        <Bot v-if="message.role==='assistant' || message.role === 'system-error'" />
        <p class="message-text">{{displayText}}</p>
    </div>
</template>

<script lang="ts" setup>
import { ref, toRefs,onMounted,watch } from 'vue';
import type{ PropType} from 'vue'
import type { MessageItem } from '../../../types/index'
import Bot from '../../Icon/Bot.vue'
onMounted(()=>{
    savedCallback.value = ()=>{
        // 检测定时器是否在运行，防止内存泄漏
        console.log('running')
        if (index < message.value.content!.length){
                index ++
                displayText.value = message.value.content!.slice(0,index)
            }else{
                enableRunning.value = false
            }
    }
    if (message.value.role === 'assistant'){
        if (!enableRunning.value){
            enableRunning.value = true
        }
    }else{
        displayText.value = message.value.content!
    }
})
let index = 0;
let displayText = ref<string>('')
let timerRef = ref<number|null>(null)
let savedCallback = ref<Function>(()=>{})
let enableRunning = ref<boolean>(false)
const props = defineProps({
    message: {
        type: Object as PropType<MessageItem>,
        required: true
}})

let { message } = toRefs(props)
watch(enableRunning,(n)=>{
    console.log("enableRunning",n);
    
    if (message.value.role !== 'assistant' ){
        displayText.value = message.value.content!
    }else{
        if (n){
            timerRef.value = setInterval(savedCallback.value,50)
        }else{
            clearInterval(timerRef.value!)
        }
    }
    return ()=>clearInterval(timerRef.value!)
})

watch(message,(n)=>{
    if (n.role === 'assistant'){
        if (!enableRunning.value){
            enableRunning.value = true
        }else{
            displayText.value = n.content!
        }
    }
})
</script>

<style scoped lang="less">
.message{
    display: flex;
    align-items: center;
    gap: 11px;
}
.bot-message svg{
    height: 35px;
    width: 35px;
    padding: 6px;
    flex-shrink: 0;
    fill: #fff;
    border-radius: 50%;

    align-self: flex-center;
}

.message .message-text{
    padding: 12px 16px;
    max-width: 75%;
    word-wrap: break-word;
    white-space: pre-line;
    font-size: 0.9rem;
}
.bot-message .message-text {
    background-color: #f6f2ff;
    border-radius: 13px 13px 13px 3px;
}
.error-message .message-text {
    color: #f00;
    background-color: #f6f2ff;
    border-radius: 13px 13px 13px 3px;
}
.user-message{
    flex-direction: column;
    align-items: flex-end;
}
.user-message .message-text {
    color: #fff;
    background-color: #6d4fc2;
    border-radius: 13px 13px 3px 13px;
}
</style>

// ai-paternal/src/components/ChatMessage.tsx
import BotIcon from "./BotIcon"
import type { MessageItem } from "../types"
import { useEffect, useState,useRef, MutableRefObject } from "react";

const ChatMessage = ({ message }: { message: MessageItem }) => {
    const [displayText,setDisplayText] = useState('')
    let index = 0
    const [enableRunning, setEnableRunning] = useState(false);
    const timerRef:MutableRefObject<number|null> = useRef(null); 
    const savedCallback = useRef(() => {}); 
    useEffect(() => {
       savedCallback.current = () => {
            // 检测定时器是否在运行，防止内存泄漏
            // console.log('running')
           if (index < message.content!.length){
                index ++
                setDisplayText(message.content!.slice(0,index))
            }else{
                setEnableRunning(false)
            }
       }
    },[])
    useEffect(() => {
        if(message.role !== 'assistant'){
            setDisplayText(message.content!)
        }else{
            if (enableRunning){
                timerRef.current = setInterval(() => {
                    savedCallback.current();
                },100)
            }else{
                clearInterval(timerRef.current!)
            }
        }
        return () => clearInterval(timerRef.current!);
    },[enableRunning])
    useEffect(() => {
        if(message.role === 'assistant'){
            if(!enableRunning){setEnableRunning(true)}

            // TypeWriter(message.content!)
        }else{
            setDisplayText(message.content!)
        }
    },[message.content])


    return (
        <><div className={`message ${message.role === 'assistant' ? 'bot' : message.role === 'system-error' ? 'error' : 'user'}-message`}>
            {message.role !=='user' && <BotIcon/>}
            <p className="message-text">{displayText}</p>
        </div>
            
        </>

    )
}

export default ChatMessage
